import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { memberRoleEnum } from "./enums";

/**
 * Application users. When Supabase Auth is configured, `id` matches
 * `auth.users.id`. With the local development auth provider, ids are
 * generated by the app.
 */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").notNull(),
    displayName: text("display_name"),
    avatarUrl: text("avatar_url"),
    lastSignInAt: timestamp("last_sign_in_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [uniqueIndex("users_email_idx").on(sql`lower(${t.email})`)],
);

export type ScoreDimensionWeights = {
  commerce: number;
  attendance: number;
  engagement: number;
  advocacy: number;
  community: number;
};

export type ScoreDimensionTargets = ScoreDimensionWeights;

/**
 * An artist is the tenant / workspace. Every artist-owned entity carries
 * `artist_id` and access is derived from `artist_members`.
 */
export const artists = pgTable(
  "artists",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    genre: text("genre"),
    country: text("country"),
    bio: text("bio"),
    avatarUrl: text("avatar_url"),
    bannerUrl: text("banner_url"),
    accentColor: text("accent_color").default("#8b5cf6").notNull(),
    followerCount: integer("follower_count").default(0).notNull(),
    /** Dimension weights (percent). Defaults to 25/25/15/20/15. */
    scoreWeights: jsonb("score_weights").$type<ScoreDimensionWeights>().notNull().default({
      commerce: 25,
      attendance: 25,
      engagement: 15,
      advocacy: 20,
      community: 15,
    }),
    /** Raw points at which a dimension sub-score reaches 100. */
    scoreTargets: jsonb("score_targets").$type<ScoreDimensionTargets>().notNull().default({
      commerce: 2500,
      attendance: 2500,
      engagement: 1200,
      advocacy: 1500,
      community: 600,
    }),
    settings: jsonb("settings").$type<Record<string, unknown>>().notNull().default({}),
    isDemo: boolean("is_demo").default(false).notNull(),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }),
    onboardedAt: timestamp("onboarded_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [uniqueIndex("artists_slug_idx").on(t.slug)],
);

export const artistMembers = pgTable(
  "artist_members",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    artistId: uuid("artist_id")
      .notNull()
      .references(() => artists.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: memberRoleEnum("role").notNull().default("viewer"),
    invitedByUserId: uuid("invited_by_user_id").references(() => users.id, { onDelete: "set null" }),
    invitedEmail: text("invited_email"),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("artist_members_artist_user_idx").on(t.artistId, t.userId),
    index("artist_members_user_idx").on(t.userId),
  ],
);

/** Pending invitations for people who do not have an account yet. */
export const artistInvites = pgTable(
  "artist_invites",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    artistId: uuid("artist_id")
      .notNull()
      .references(() => artists.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    role: memberRoleEnum("role").notNull().default("viewer"),
    invitedByUserId: uuid("invited_by_user_id").references(() => users.id, { onDelete: "set null" }),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("artist_invites_artist_idx").on(t.artistId),
    uniqueIndex("artist_invites_token_idx").on(t.tokenHash),
  ],
);
